apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-addressbook
  namespace: harness-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-addressbook
  template:
    metadata:
      labels:
        app: my-addressbook
    spec:
      containers:
        - name: my-addressbook-app
          image: harness-poc/harness-poc:v1.0.0
          ports:
            - containerPort: 8080
