apiVersion: v1
kind: Service
metadata:
  name: my-addressbook
  namespace: harness-poc
spec:
  selector:
    app: my-addressbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090
  type: NodePort
